export const STRIKERATE_LIST_IS_LOADING = 'STRIKERATE_LIST_IS_LOADING';
export const STRIKERATE_LIST_LOAD_SUCCESS = 'STRIKERATE_LIST_LOAD_SUCCESS';
export const STRIKERATE_LIST_LOAD_ERROR = 'STRIKERATE_LIST_LOAD_ERROR';