export const DELIVERY_LIST_IS_LOADING = 'DELIVERY_LIST_IS_LOADING';
export const DELIVERY_LIST_LOAD_SUCCESS = 'DELIVERY_LIST_LOAD_SUCCESS';
export const DELIVERY_LIST_LOAD_ERROR = 'DELIVERY_LIST_LOAD_ERROR';